name: Build and Release Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [linux, win, macos]
        include:
          - os: linux
            target: node18-linux-x64
            file: discordjsaichat-linux
          - os: win
            target: node18-win-x64
            file: discordjsaichat-win.exe
          - os: macos
            target: node18-macos-x64
            file: discordjsaichat-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Install zip (Linux/macOS only)
        if: matrix.os != 'win'
        run: sudo apt-get update && sudo apt-get install -y zip || true

      - name: Build binary for ${{ matrix.os }}
        run: pkg . --target=${{ matrix.target }} --output=${{ matrix.file }}

      - name: Prepare artifact directory
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          mv ${{ matrix.file }} artifacts/${{ matrix.os }}/
          cp .env.example status.json artifacts/${{ matrix.os }}/

      - name: Zip artifact
        if: matrix.os != 'win'
        run: |
          cd artifacts/${{ matrix.os }}
          zip -r ../../${{ matrix.os }}.zip .

      - name: Zip artifact (Windows)
        if: matrix.os == 'win'
        run: |
          powershell Compress-Archive -Path artifacts/win/* -DestinationPath win.zip

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-zip
          path: ${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Download all zipped artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display downloaded artifacts
        run: ls -R dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: v${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/linux-zip/linux.zip
            dist/win-zip/win.zip
            dist/macos-zip/macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
