name: Build and Release Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, win, macos]
        include:
          - os: linux
            target: node18-linux-x64
            file: discordjsaichat-linux
          - os: win
            target: node18-win-x64
            file: discordjsaichat-win.exe
          - os: macos
            target: node18-macos-x64
            file: discordjsaichat-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build binary for ${{ matrix.os }}
        run: pkg . --target=${{ matrix.target }} --output=${{ matrix.file }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: ${{ matrix.file }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display artifacts
        run: ls -R dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: v${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/discordjsaichat-linux/discordjsaichat-linux
            dist/discordjsaichat-win.exe/discordjsaichat-win.exe
            dist/discordjsaichat-macos/discordjsaichat-macos
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
